language: cpp
compiler: gcc
install:
    - sudo apt-get -y install cmake

addons:
    coverity_scan:
        project:
            name: "lmsorenson/CommonCpp"
            description: "CommonCpp"
        notification_email: lsorenson20@gmail.com
        build_command_prepend:
        build_command: 
            - ./build-scripts/generate-tests-makefile.sh
            - ./build-scripts/build-tests.sh
        branch_pattern: branch-name
