language: cpp
compiler: gcc

matrix:
    include:
        - os: osx
          osx_image: xcode8
          env:
              - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

        - os: osx
          osx_image: xcode8
          env:
              - MATRIX_EVAL="brew install gcc5 && CC=gcc-5 && CXX=g++-5"

        - os: osx
          osx_image: xcode8
          env:
              - MATRIX_EVAL="brew install gcc6 && CC=gcc-6 && CXX=g++-6"

        - os: osx
          osx_image: xcode8
          env:
              - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"

        #try xcode 9
        - os: osx
            osx_image: xcode9
            env:
              - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"

        - os: linux
          install:
              - sudo apt-get -y install cmake
before_install:
    - eval "${MATRIX_EVAL}"
install:
    - eval "${MATRIX_EVAL}"
script:
    - ./build-scripts/generate-tests-makefile.sh
    - ./build-scripts/build-tests.sh