name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: build_job
    runs-on: macOS-10.14
    
    steps:
    - name: sub
      run: |
        pwd
        git clone --recurse-submodules https://$WORKFLOW_KEY@github.com/lmsorenson/CommonCpp.git
        #git submodule checkout --init --recursive
    - name: pwd
      run: pwd
    - name: make cmake directory
      run: |
        mkdir tests
        ls ..
        cd ./tests/
        pwd
        mkdir cmake
        ls
        cd ./cmake 
        pwd
        ls
        cmake ..
        make
      #
    #- name: make
    #  run: make
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
