name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: build_job
    runs-on: |
        macOS-10.14
        macOS-latest
    
    steps:
    - name: sub
      run: |
        pwd
        git clone --recurse-submodules https://${{secrets.NAME_U}}:${{secrets.WF_NAME}}@github.com/lmsorenson/CommonCpp.git
        #git submodule checkout --init --recursive
    - name: pwd
      run: pwd
    - name: make cmake directory
      run: |
        ls
        cd CommonCpp/tests/
        pwd
        mkdir cmake
        ls
        cd ./cmake 
        pwd
        ls
        cmake ..
        make
    - name: run tests
      run: ./CommonCpp/tests/out/tests
      #
    #- name: make
    #  run: make
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
