name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: Build, Run, Test
    runs-on: macOS-latest
    
    steps:
    - name: Checkout source code
      run: |
        git clone --recurse-submodules https://${{secrets.NAME_U}}:${{secrets.WF_NAME}}@github.com/lmsorenson/CommonCpp.git
    - name: Compile the project
      run: |
        cd CommonCpp/tests/
        mkdir cmake
        cd ./cmake 
        cmake ..
        make
    - name: Validation Test
      run: |
        cd ./CommonCpp/tests/out/
        sudo ./tests
        ls ./CommonCpp/tests/test_data/Write/
