name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: build_job
    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@v1
    - name: pwd
      run: pwd
    - name: make cmake directory
      run: mkdir ./tests/cmake
    - name: configure
      run: |
      cd ./tests/cmake 
      cmake ..
      make
    #- name: make
    #  run: make
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
